duke-libraries/ddr-models

app/models/collection.rb
spec/models/collection_spec.rb

Addresses https://github.com/duke-libraries/dul-hydra/issues/1243 .

Collection object set to be governed by itself at creation

---

lib/ddr/managers/permanent_id_manager.rb

Corrected the value of Ddr::Managers::PermanentIdManager::TARGET_BASE_URL

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/admin_metadata_datastream.rb
lib/ddr/datastreams/descriptive_metadata_datastream.rb
lib/ddr/datastreams/metadata_datastream.rb
lib/ddr/datastreams/struct_metadata_datastream.rb
spec/models/descriptive_metadata_datastream_spec.rb

Move selected methods from DescriptiveMetadataDatastream to MetadataDatastream.
Refactor #term_names class methods.
Closes #141

Create Ddr::Datastreams::MetadataDatastream superclass.

---

lib/ddr/managers/permanent_id_manager.rb

Changed permanent id update event summary constant

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/structural_metadata_datastream.rb
lib/ddr/models/has_struct_metadata.rb

Rename StructMetadataDatastream to StructuralMetadataDatastream.

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/models/has_admin_metadata.rb

Renamed AdminMetadataDatastream to AdministrativeMetadataDatastream

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Moves the methods from ddr-public

add license methods to SolrDocument; closes #163

---

lib/ddr/auth/roles/metadata_editor.rb
spec/auth/roles/metadata_editor_spec.rb

Added :download permission to the MetadataEditor role

---

lib/ddr/auth/permission.rb
lib/ddr/auth/roles/curator.rb
lib/ddr/auth/roles/editor.rb
lib/ddr/auth/roles/owner.rb
spec/auth/permission_spec.rb
spec/managers/role_manager_spec.rb

Renamed the :upload permission to :replace

---

lib/ddr/managers/permanent_id_manager.rb
lib/ddr/models.rb

Moves permanent identifier target URL base from constant to configurable setting

---

ddr-models.gemspec
lib/ddr/models.rb
lib/ddr/models/has_content.rb

Removed hydra-derivatives dependency

---

lib/ddr/auth/role_based_access_controls_enforcement.rb
lib/ddr/auth/roles/role_set.rb
lib/ddr/index_fields.rb
lib/ddr/managers.rb
lib/ddr/managers/abstract_role_manager.rb
lib/ddr/managers/role_manager.rb
lib/ddr/managers/solr_document_role_manager.rb
lib/ddr/models/solr_document.rb
spec/auth/roles/role_set_spec.rb
spec/controllers/including_role_based_access_controls_enforcement_spec.rb
spec/managers/role_manager_spec.rb
spec/models/solr_document_spec.rb

Does *not* implement updated Ability class to use roles for authz.

Finishes model-level work on roles

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Adds `local_id` instance method to SolrDocument

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Adds `#admin_set` to SolrDocument

---

lib/ddr/models/fixity_checkable.rb
lib/ddr/models/has_content.rb
spec/support/shared_examples_for_ddr_models.rb
spec/support/shared_examples_for_has_content.rb

Added event-related methods to duck-type SolrDocument

---

lib/ddr/models/version.rb

Version 1.16.0 for ddr-models.
Adds configuration option for which derivatives to generate.
Adds index fields for admin set and collection facets.

Release 1.16

---

lib/ddr/jobs/migrate_legacy_authorization.rb
spec/auth/legacy_authorization_spec.rb
spec/jobs/migrate_legacy_authorization_spec.rb

Added tests to verify migration

Changed the authorization migration job

---

app/models/item.rb
lib/ddr/datastreams/structural_metadata_datastream.rb
lib/ddr/models.rb
lib/ddr/models/has_struct_metadata.rb
lib/ddr/models/struct_div.rb
lib/ddr/models/structure.rb
spec/factories/structure_factories.rb
spec/models/has_struct_metadata_spec.rb
spec/models/item_spec.rb
spec/models/struct_div_spec.rb
spec/models/structure_spec.rb
spec/spec_helper.rb
spec/support/structural_metadata_helper.rb

XML document actually contains only structMap element.  No need identified for fileSec element.

Revised handling of structural metadata; closes #255.

---

db/migrate/20150710211530_change_events_exception_to_text.rb
db/migrate/20150713171838_add_limit_to_events_exception.rb
lib/ddr/auth/user.rb
lib/ddr/events/event.rb
spec/dummy/app/models/user.rb
spec/dummy/db/schema.rb

Closes #277
Added migration to change event exception field to text - fixes #263
Removed Blacklight::User from Ddr::Auth::User - closes #235

Decoupled Ddr::Events::Event from Ddr::Auth::User

---

lib/ddr/contacts.rb
lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index_fields.rb
lib/ddr/models.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/indexing.rb
lib/ddr/models/solr_document.rb
lib/ddr/models/version.rb
lib/ddr/vocab.rb
lib/ddr/vocab/contact.rb
spec/contacts/contacts_spec.rb
spec/models/has_admin_metadata_spec.rb
spec/models/solr_document_spec.rb

Initial implementation based on YAML file contact information.

Research help contact functionality; closes #291.

---

lib/ddr/auth/ability_definitions/role_based_ability_definitions.rb
lib/ddr/auth/role_based_access_controls_enforcement.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/solr_document.rb
spec/auth/ability_spec.rb
spec/models/solr_document_spec.rb

Removed unused methods from Ddr::Models::HasAdminMetadata
Added `effective_permissions` method to HasAdminMetadata and SolrDocument

Added override of Hydra::AccessControlsEnforcement#enforce_show_permissions

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/fits_datastream.rb
lib/ddr/models/has_content.rb

Adds "fits" datastream to content-bearing objects

Added Ddr::Datastreams::FitsDatastream

---

lib/ddr/datastreams/fits_datastream.rb
lib/ddr/managers.rb
lib/ddr/managers/technical_metadata_manager.rb
lib/ddr/models/has_content.rb
spec/fixtures/fits/document.xml
spec/fixtures/fits/image.xml
spec/managers/technical_metadata_manager_spec.rb

Defines mapping of technical metadata reader methods to data.
Closes #303

Added Ddr::Managers::TechnicalMetadataManager

---

lib/ddr/models/has_admin_metadata.rb

Restored Ddr::Models::HasAdminMetadata#inherited_roles

---

lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/version.rb

Restored Ddr::Models::HasAdminMetadata#inherited_roles to release-2.0

---

lib/ddr/auth/ability_definitions/datastream_ability_definitions.rb

Added fits datastream ability

---

lib/ddr/datastreams/fits_datastream.rb
lib/ddr/managers/technical_metadata_manager.rb
spec/managers/technical_metadata_manager_spec.rb

Merges content datastream metadata into results

Enhancements to TechnicalMetadataManager

---

lib/ddr/index_fields.rb
spec/controllers/including_role_based_access_controls_enforcement_spec.rb

Changes indexing of policies roles and resources roles.

---

lib/ddr/datastreams/fits_datastream.rb
spec/datastreams/fits_datastream_spec.rb
spec/managers/technical_metadata_manager_spec.rb

Excludes Exiftool lastmodified date from technical metadata

---

lib/ddr/index_fields.rb
lib/ddr/models.rb
lib/ddr/models/indexing.rb
lib/ddr/models/year_facet.rb
spec/models/year_facet_spec.rb

Adds year facet index field

---

README.md
ddr-models.gemspec
lib/ddr/actions.rb
lib/ddr/actions/virus_check.rb
lib/ddr/events/virus_check_event.rb
lib/ddr/models/file_management.rb
spec/spec_helper.rb

Adds Ddr::Actions::VirusCheck as a functional replacement for ddr-antivirus.

---

lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models/indexing.rb
spec/models/has_admin_metadata_spec.rb

Adds DOI index field constant
Indexes DOI values under "doi_ssim"
Closes #355

Adds :doi property to adminMetadata

---

ddr-models.gemspec
lib/ddr/models.rb
lib/ddr/models/admin_set.rb
lib/ddr/models/license.rb
spec/models/admin_set_spec.rb
spec/models/effective_license_spec.rb
spec/models/license_spec.rb

Upgrades ddr-aux-client to minimum v1.2.1.

Adds `Ddr::Models::AdminSet`

---

lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models.rb
lib/ddr/models/finding_aid.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/indexing.rb
lib/ddr/models/solr_document.rb
lib/ddr/vocab/asset.rb
spec/models/finding_aid_spec.rb

Adds support for linking to finding aids via EAD identifier.

---

ddr-models.gemspec
lib/ddr/models/version.rb

Bumps version to 2.1.2
Closes #401

Upgrades ddr-aux-client to v1.2.2

---

lib/ddr/models.rb
lib/ddr/models/describable.rb
lib/ddr/models/file_management.rb
lib/ddr/models/has_multires_image.rb
lib/ddr/models/metadata/descriptive_metadata.rb
lib/ddr/models/metadata/metadata_mapper.rb
lib/ddr/models/metadata/metadata_mappers.rb
lib/ddr/models/metadata/metadata_vocabularies.rb
lib/ddr/models/metadata/metadata_vocabulary.rb
spec/support/shared_examples_for_describables.rb

@coblej Fixes Item model spec tests that I was supposed to fix.

WIP [ci skip]

---

lib/ddr/models/finding_aid.rb
spec/models/finding_aid_spec.rb

Revises FindingAid fields per #402.

---

Gemfile
ddr-models.gemspec
lib/ddr/datastreams/datastream_behavior.rb
spec/auth/roles/role_spec.rb
spec/models/active_fedora_datastream_spec.rb

Fixes role tests by upgrading active-triples to v0.7.2.
Upgrades active-fedora to post-v9.5.0 commit on master.

Fixes datastream tests except checksum validation.

---

Gemfile
ddr-models.gemspec

Upgrades ddr-antivirus to ~> 2.1.1.

Upgrades active-fedora to ~> 9.6.2.

---

lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/indexing.rb
lib/ddr/vocab/asset.rb
spec/models/indexing_spec.rb

Adds ArchivesSpace ID property to adminMetadata.

---

lib/ddr/auth/roles/role_attribute.rb
spec/auth/roles/role_spec.rb

Ddr::Auth::Roles::RoleAttribute coerces Array

---

lib/ddr/auth/roles/role_set_manager.rb
spec/auth/roles/role_set_manager_spec.rb

Ddr::Auth::Roles::RoleSetManager#granted coerces argument to Role

---

lib/ddr/models.rb
lib/ddr/models/admin_set.rb
lib/ddr/models/contact.rb
lib/ddr/models/error.rb
lib/ddr/models/licenses/license.rb
spec/models/admin_set_spec.rb
spec/models/contact_spec.rb
spec/models/has_admin_metadata_spec.rb
spec/models/license_spec.rb
spec/models/solr_document_spec.rb

Fixes .call class methods on ActiveResource models to return instances

---

config/locales/ddr-models.en.yml
ddr-models.gemspec
lib/ddr/index.rb
lib/ddr/index/csv_query_result.rb
lib/ddr/index/field.rb
lib/ddr/index/fields.rb
lib/ddr/index/filter.rb
lib/ddr/index/filters.rb
lib/ddr/index/queries.rb
lib/ddr/index/query.rb
lib/ddr/index/query_builder.rb
lib/ddr/index/query_clause.rb
lib/ddr/index/query_params.rb
lib/ddr/index/query_value.rb
lib/ddr/index/sort_order.rb
spec/index/fields_spec.rb
spec/index/filter_spec.rb
spec/index/filters_spec.rb
spec/index/queries_spec.rb
spec/index/query_builder_spec.rb
spec/index/query_clause_spec.rb
spec/index/query_spec.rb

Enhancements to and refactorings of Ddr::Index.

---

lib/ddr/index/query.rb
spec/index/query_spec.rb

Define equality of Ddr::Index::Query instances.

---

lib/ddr/models/has_content.rb
lib/ddr/models/version.rb
spec/support/shared_examples_for_has_content.rb

Delete existing FITS data when new content is persisted.

---

lib/ddr/index/fields.rb
lib/ddr/models/indexing.rb
lib/ddr/models/version.rb
spec/models/indexing_spec.rb

Index creation date of content datastream.

---

lib/ddr/events.rb
lib/ddr/events/migration_event.rb
lib/ddr/notifications.rb
spec/models/events_spec.rb

Adds Ddr::Notifications::MIGRATION
Closes #522

Adds Ddr::Events::MigrationEvent

---

.gitignore
lib/ddr/index/query_builder.rb
lib/ddr/models.rb
lib/ddr/models/solr_document.rb

Remove 3.x deprecations

---

config/initializers/subscriptions.rb
lib/ddr/events/event.rb
lib/ddr/jobs.rb
lib/ddr/jobs/delete_multires_image.rb
lib/ddr/models/base.rb
lib/ddr/models/has_multires_image.rb
lib/ddr/notifications.rb
spec/models/has_multires_image_spec.rb

Deletes multires image file after destroy.

---

app/models/attachment.rb
app/models/collection.rb
app/models/component.rb
app/models/item.rb
app/models/target.rb
lib/ddr/auth.rb
lib/ddr/auth/ability.rb
lib/ddr/auth/ability_definitions/publication_ability_definitions.rb
lib/ddr/auth/permissions.rb
lib/ddr/models/base.rb
lib/ddr/models/has_admin_metadata.rb
spec/auth/ability_spec.rb
spec/models/attachment_spec.rb
spec/models/collection_spec.rb
spec/models/component_spec.rb
spec/models/item_spec.rb
spec/models/target_spec.rb
spec/support/shared_examples_for_publication.rb

Also add #publishable? method to Ddr::Managers::WorkflowManager.

Add abilities to publish and unpublish; closes #556

---

lib/ddr/auth.rb
lib/ddr/auth/ability.rb
lib/ddr/auth/ability_definitions/lock_ability_definitions.rb
spec/auth/ability_spec.rb

Deny permissions that change object if object locked; closes #606.

---

Gemfile

This seems to fix circular dependency issues.

Pinned linkeddata to <= 1.99.0

---

lib/ddr/index/fields.rb
lib/ddr/managers/technical_metadata_manager.rb
lib/ddr/models/files/fits_xml_file.rb
spec/index/fields_spec.rb
spec/managers/technical_metadata_manager_spec.rb

Ddr::Index:Fields::TECHMD_MESSAGE

Adds index field for FITS file status message(s).

---

lib/ddr/index/fields.rb
lib/ddr/models/attached_file_profile.rb
lib/ddr/models/attached_files_profile.rb
lib/ddr/models/base.rb
lib/ddr/models/solr_document.rb
spec/models/attached_files_profile_spec.rb
spec/models/solr_document_spec.rb

Attached files profile now only includes attached files having content.

Changes indexing of attached files profiles to :stored_sortable.

---

lib/ddr/index/fields.rb
lib/ddr/managers/technical_metadata_manager.rb
lib/ddr/models/files/fits_xml_file.rb
spec/index/fields_spec.rb
spec/managers/technical_metadata_manager_spec.rb

Adds indexed md5checksum method to technical metadata.

---

lib/ddr/index/abstract_query_result.rb
lib/ddr/index/connection.rb
lib/ddr/index/csv_query_result.rb
lib/ddr/index/query_result.rb
lib/ddr/index/response.rb

Connection methods are called statically.
QueryResult adds #objects enumerator.
QueryResult adds #facet_fields.

Some refactoring of Ddr::Index

---

lib/ddr/models/base.rb
lib/ddr/models/version.rb
spec/support/shared_examples_for_ddr_models.rb

Disables auto-versioning pending reconsideration of how versioning is handled.

Disable auto-versioning on save.

---

lib/ddr/auth/roles/role_set.rb
spec/auth/role_set_spec.rb

Ddr::Auth::RoleSet delegates `<<' to :roles

---

lib/ddr/models/solr_document.rb

SolrDocument caches research_help

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Improve efficiency of SolrDocument#multires_image_file_paths

---

lib/ddr/index/filter.rb
lib/ddr/index/query_builder.rb
lib/ddr/index/query_clause.rb
spec/index/filter_spec.rb
spec/index/query_builder_spec.rb
spec/index/query_clause_spec.rb

Adds `join' to QueryBuilder DSL

---

lib/ddr/index/filter.rb
lib/ddr/index/query_builder.rb
lib/ddr/index/query_clause.rb
spec/index/filter_spec.rb
spec/index/query_builder_spec.rb
spec/index/query_clause_spec.rb

Adds `regexp' to query builder DSL

---

config/initializers/active_fedora_file.rb
lib/ddr/models/version.rb
lib/ddr/notifications.rb
spec/models/active_fedora_file_spec.rb

Adds after_save notification to AF::File.

Hotfix v3.0.7

---

lib/ddr/events.rb
lib/ddr/events/replication_event.rb
lib/ddr/models/version.rb
spec/models/events_spec.rb

Adds Ddr::Events::ReplicationEvent

Hotfix v3.0.8

---

lib/ddr/auth.rb
lib/ddr/auth/ability.rb
lib/ddr/auth/ability_definitions/admin_set_ability_definitions.rb
lib/ddr/auth/ability_factory.rb
lib/ddr/auth/abstract_ability.rb
lib/ddr/auth/auth_context.rb
lib/ddr/auth/auth_context_factory.rb
lib/ddr/models/version.rb
spec/auth/ability_factory_spec.rb
spec/auth/ability_spec.rb
spec/support/shared_examples_for_auth_contexts.rb

Adds code to Ddr::Auth to support the implementation of
"metadata manager".

Version 2.4.16

---

lib/ddr/models/base.rb
spec/support/shared_examples_for_ddr_models.rb

The notification payload includes pid, model, changes (tracked
by ActiveModel::Dirty), and boolean for whether the save created
the object or not.

Added around_save callback to send notification to subscribers

---

lib/ddr/datastreams/fits_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/managers/technical_metadata_manager.rb
spec/index/fields_spec.rb
spec/managers/technical_metadata_manager_spec.rb

Indexes iccProfileName and iccProfileVersion technical metadata

---

lib/ddr/index/fields.rb

Freezes Ddr::Index::Fields class variables @techmd and @descmd.

---

lib/ddr/managers/workflow_manager.rb
lib/ddr/models/version.rb

Fixes DDR-257: Publish only includes 1000 descendants

Hotfix v2.5.1

---

lib/ddr/managers/permanent_id_manager.rb

Updates permanent URL base to https://idn.duke.edu/

---

config/initializers/devise.rb

Devise config updated to map duDukeID to uid when eppn is not present.

---

lib/ddr/models/has_admin_metadata.rb

Add 'doi' to list of adminMetadata attributes.

---

lib/ddr/models/base.rb
spec/support/shared_examples_for_ddr_models.rb

"workflow" inserted between state and model.

Workflow change notification names modified.

---

ddr-models.gemspec
lib/ddr/models/year_facet.rb
spec/models/year_facet_spec.rb

@dchandekstark this pull request copies the EDTF date support that is in develop into f3-develop.

Backport EDTF date parsing to fix year_facet vals

---

lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models/base.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/indexing.rb
lib/ddr/vocab/asset.rb
spec/models/indexing_spec.rb
spec/support/shared_examples_for_ddr_models.rb

Adds ingested_by and ingestion_date properties to Ddr::Models::Base

---

app/models/item.rb
config/initializers/subscriptions.rb
lib/ddr/events/deletion_event.rb
lib/ddr/events/event.rb
lib/ddr/events/ingestion_event.rb
lib/ddr/index/filter.rb
lib/ddr/models/base.rb
spec/models/events_spec.rb
spec/models/item_spec.rb
spec/support/shared_examples_for_ddr_models.rb

Removes explicit usage of IngestionEvent and CreationEvent

---

app/models/component.rb
lib/ddr/models/structure.rb
spec/models/component_spec.rb
spec/models/structure_spec.rb

Add convenience methods related to use.  Other minor refactoring.

Adopt PCDM File Use terms for structural metadata.

---

app/models/collection.rb
lib/ddr/models/base.rb
spec/models/collection_spec.rb

Grants policy role to metadata managers on collection be default.

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/intermediate_file_datastream.rb
lib/ddr/models/has_intermediate_file.rb

Covert intermediate file datastream to external storage.

---

lib/ddr/datastreams/external_file_datastream.rb
lib/ddr/models/file_management.rb
spec/models/file_management_spec.rb

- Sets dsLocation to nil after destroy
- Fixes setting of original_filename

Fixes a couple of bugs with external datastreams.

---

lib/ddr/index/csv_query_result.rb
spec/index/csv_query_result_spec.rb

Adds CSV converters to CSVQueryResult to handle Solr CSV writer escaping

---

lib/ddr/datastreams/metadata_datastream.rb
spec/models/descriptive_metadata_datastream_spec.rb

Strips whitespace from metadata values.

---

lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/indexing.rb
lib/ddr/vocab/asset.rb
spec/models/indexing_spec.rb

Adds `affiliation` property to administrative metadata.

---

lib/ddr/events/update_event.rb

Removes possibly inaccurate/misleading empty "attributes changed"
