duke-libraries/ddr-models

Rakefile
ddr-models.gemspec
lib/ddr/models/engine.rb

Set `DeviseRemoteUser.login_url` to a Proc which resolves to a URL
for logging into Shib and returning to the previous URL (REQUEST_URI).

Upgraded devise-remote-user to ~> 0.5.0 to get the `login_url` setting.

---

config/locales/groups.en.yml

This is a light weight solution motivated by the use of Grouper groups.  While a static file initially duplicates Grouper data, it establishes the pattern and could be overridden by dynamically updated files on the server.

Added I18n config to support labels for groups

---

db/migrate/20150130134416_add_user_key_to_events.rb
lib/ddr/auth/ability.rb
lib/ddr/events/event.rb
spec/dummy/db/schema.rb
spec/models/ability_spec.rb
spec/support/shared_examples_for_events.rb

To update the events table after running the migration, run this code:
```ruby
Ddr::Events::Event.joins(:user).includes(:user).find_each do |e|
e.user_key = e.user.user_key
end
```
After the data update the assoiciation should removed on the user_id
column dropped from the events table.

Adds user_key to events in order to decouple events from users.

---

config/initializers/devise.rb
lib/ddr/auth.rb
lib/ddr/auth/failure_app.rb
spec/controllers/application_controller_spec.rb
spec/routing/user_routing_spec.rb
spec/spec_helper.rb

Replaces default Devise failure app.
Adds a configuration setting `Ddr::Auth.require_shib_user_authn` (default: `false`)
to force authentication failure response (via the failure app) to redirect to shib login instead of
default login form.
Closes #106
Upgrade notes:
- Set `Ddr::Auth.require_shib_user_authn = true` in production evnironment where
desired to require Shib authentication.

Implements a custom failure app for Warden 

---

app/controllers/users/sessions_controller.rb
spec/controllers/users/sessions_controller_spec.rb

Reason: The flash is displayed after the user authns to shib and returns
to the app, at which point the message is irrelevant ("sign in or sign up")
and confusing.

Remove the failure app alert from the flash when shib authn is required

---

ddr-models.gemspec

Version number has **not** been changed in the hotfix branch.

Hotfix: upgraded ezid-client to ~> 1.0

---

lib/ddr/models/has_content.rb
lib/ddr/models/has_struct_metadata.rb
spec/models/has_struct_metadata_spec.rb

Uses an after_create callback to assign default values (as appropriate) for any structural metadata
attributes that do not have values assigned as part of the initial creation process.

Assign default structural metadata; closes #134

---

config/initializers/subscriptions.rb
lib/ddr/events.rb
lib/ddr/events/deletion_event.rb
lib/ddr/events/event.rb
lib/ddr/models/base.rb
lib/ddr/notifications.rb
spec/models/events_spec.rb
spec/support/shared_examples_for_ddr_models.rb
spec/support/shared_examples_for_event_loggables.rb
spec/support/shared_examples_for_events.rb

Notes:
- Due to implementation of callbacks in ActiveFedora, a DeletionEvent
is only created after #destroy, not #delete. We may want to consider
patching #delete to ensure that a DeletionEvent is always logged.
- The validation of object existence has been removed from Ddr::Events::Event.
Although the validation made some sense of events other than deletion,
in practice, since event PIDs are not user-entered, it simply added
a repository object load.

Adds DeletionEvent - closes #103

---

lib/ddr/models/has_children.rb
lib/ddr/models/version.rb
spec/models/has_children_spec.rb

Fixes #165
Also uses ActiveFedora query methods instead of SolrService and find.
The conditional branch which uses the deprecated contentMetadata
datastream is NOT tested, and was left in only for compatibility
with dul-hydra.

Ddr::Models::HasChildren#first_child returns nil if object has no children

---

app/models/component.rb
lib/ddr/datastreams.rb
lib/ddr/derivatives.rb
lib/ddr/derivatives/generator.rb
lib/ddr/derivatives/png_generator.rb
lib/ddr/derivatives/ptif_generator.rb
lib/ddr/managers.rb
lib/ddr/managers/derivatives_manager.rb
lib/ddr/models.rb
lib/ddr/models/engine.rb
lib/ddr/models/error.rb
lib/ddr/models/file_management.rb
lib/ddr/models/has_content.rb
lib/ddr/models/has_multires_image.rb
lib/ddr/utils.rb
spec/managers/derivatives_manager_spec.rb
spec/models/file_management_spec.rb
spec/spec_helper.rb
spec/support/shared_examples_for_has_content.rb
spec/utils_spec.rb

Adds a DerivativesManager to manage creation, change, and deletion of
various derivatives based on the 'content' datastream.  By default
derivatives are generated asynchronously, with a separate Resque job for
each derivative to be generated.
Adds a 'multiresImage' datastream to hold PTIF's, JPEG2000's, or other
multi-resolution images for presentation by an image server.
Closes #170.

Refactor derivative generation; add PTIF derivative generation.

---

ddr-models.gemspec
lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb
spec/spec_helper.rb

This is a hotfix in support of https://github.com/duke-libraries/ddr-public/issues/102

Adds `#permanent_id` method to SolrDocument

---

ddr-models.gemspec
lib/ddr/auth/group.rb
lib/ddr/managers/role_manager.rb
spec/auth/group_spec.rb
spec/managers/role_manager_spec.rb

Adds delegation of missing methods on Ddr::Auth::Group to the group
name as a string, also for backward-compatibility
Closes #203

Readds access to the legacy downloader role data for backward-compatibility

---

lib/ddr/models.rb
lib/ddr/models/base.rb
lib/ddr/models/engine.rb
lib/ddr/models/error.rb
spec/models/active_fedora_base_spec.rb

objects by calling .find on the wrong class.

Patches ActiveFedora 7 behaviors in order to prevent mis-casting of

---

lib/ddr/datastreams.rb
lib/ddr/datastreams/plain_text_datastream.rb
lib/ddr/index_fields.rb
lib/ddr/models/base.rb
lib/ddr/models/has_content.rb
lib/ddr/models/indexing.rb
spec/models/has_admin_metadata_spec.rb
spec/support/shared_examples_for_has_content.rb

Closes #224
- Adds `Ddr::Datastreams::PlainTextDatastream` to set default mimeType to
"text/plain"
- Adds `#has_extracted_text?` method to `Ddr::Models::Base`.
- Adds unstored text index field (extracted_text_teim) for indexing extracted text.

Adds datastream for extracted text

---

lib/ddr/index_fields.rb
lib/ddr/models/describable.rb
lib/ddr/models/has_children.rb
lib/ddr/models/indexing.rb
lib/ddr/utils.rb
spec/models/has_children_spec.rb
spec/support/shared_examples_for_ddr_models.rb
spec/support/shared_examples_for_indexing.rb

Removes Ddr::IndexFields::IDENTIFIER.
Adds Ddr::IndexFields::IDENTIFIER_ALL that includes dcterms:identifier, local_id, permanent_id, and pid.

Changes indexing strategy for identifiers.  Closes #257.

---

lib/ddr/auth/legacy/legacy_authorization.rb
lib/ddr/auth/legacy/legacy_default_permissions.rb
lib/ddr/auth/legacy/legacy_permissions.rb
lib/ddr/auth/legacy/legacy_roles.rb
lib/ddr/auth/roles/role_set.rb
lib/ddr/jobs.rb
lib/ddr/jobs/migrate_legacy_authorization.rb
lib/ddr/models/has_admin_metadata.rb
spec/auth/legacy_authorization_spec.rb
spec/auth/legacy_default_permissions_spec.rb
spec/auth/legacy_permissions_spec.rb
spec/auth/legacy_roles_spec.rb
spec/jobs/migrate_legacy_authorization_spec.rb

Note: An important bug was also fixed in Ddr::Models::HasAdminMetadata
which caused role information to remain stale following a reload.

Adds Ddr::Jobs::MigrateLegacyAuthorization job for authz migration.

---

lib/ddr/index_fields.rb
lib/ddr/vocab/asset.rb

Remove FILE_USE, ORDER, FILE_GROUP from Ddr::IndexFields.
Remove fileUse, order, fileGroup properties from Ddr::Vocab::Asset.

Remove references to old structural metadata attributes; closes #256.

---

lib/ddr/models/struct_div.rb
spec/models/struct_div_spec.rb

Changes also to some attribute and method names.

Refactor StructDiv methods to return all nested objects; closes #278.

---

lib/ddr/index_fields.rb
lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Explicitly defined methods that used the deprecated method
Blacklight::Solr::Document#get to return index field values
are now handled by method_missing.

Refactored Ddr::Models::SolrDocument to remove deprecations

---

lib/ddr/auth/ability_definitions/collection_ability_definitions.rb
lib/ddr/auth/auth_context.rb
lib/ddr/auth/dynamic_groups.rb
lib/ddr/auth/groups.rb
spec/auth/ability_spec.rb
spec/auth/groups_spec.rb
spec/support/shared_examples_for_auth_contexts.rb

Removes SUPERUSERS and COLLECTION_CREATORS from Ddr::Auth::Groups.
Fixes #296

Fixes issues with superuser and collection creators groups

---

lib/ddr/auth/role_based_access_controls_enforcement.rb
spec/controllers/including_role_based_access_controls_enforcement_spec.rb

Was causing policy roles not to be granted in gated discovery.
Fixes #318

Fixes bug in Ddr::Auth::RoleBasedAccessControlsEnforcement#policy_role_filters

---

lib/ddr/datastreams/fits_datastream.rb
lib/ddr/managers/technical_metadata_manager.rb
spec/managers/technical_metadata_manager_spec.rb

This is to avoid confusion about what constitutes technical metadata.

Removes datastream metadata from media_type and file_size.

---

lib/ddr/datastreams/fits_datastream.rb
lib/ddr/managers/technical_metadata_manager.rb
spec/managers/technical_metadata_manager_spec.rb

The API of TechnicalMetadataManager has not changed.

Moves delegation of FITS terms to datastream, where it belongs.

---

lib/ddr/datastreams/datastream_behavior.rb
spec/models/active_fedora_datastream_spec.rb

Method yields a new (closed) tempfile containing the datastream content
to the block.  The tempfile is automatically removed on exiting the block.
An exception is raised if the datastream is empty.  The default file name
is prefixed by the pid (subbing _ for :) and suffixed by the extension
for the datastream media type.  Use the `:prefix` and `:suffix` options
to override.

Adds `tempfile` method to DatastreamBehavior

---

lib/ddr/index.rb
lib/ddr/index/connection.rb
lib/ddr/index/csv_query_result.rb
lib/ddr/index/document_builder.rb
lib/ddr/index/field.rb
lib/ddr/index/fields.rb
lib/ddr/index/filter.rb
lib/ddr/index/filters.rb
lib/ddr/index/query.rb
lib/ddr/index/query_builder.rb
lib/ddr/index/query_result.rb
lib/ddr/index/response.rb
lib/ddr/index/ruby_query_result.rb
lib/ddr/index/unique_key_field.rb
lib/ddr/index_fields.rb
lib/ddr/models.rb
lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Ddr::IndexFields is now deprecated; use Ddr::Index::Fields.
Ddr::Index::Query is a first cut at encapsulating index query formulation.

New module Ddr::Index

---

lib/ddr/index.rb
lib/ddr/index/query.rb
lib/ddr/index/query_result.rb
lib/ddr/index/ruby_query_result.rb

`Ddr::Index::RubyQueryResult#pids` yields the pids from the result documents.
`Ddr::Index.pids` yields the pids for all docs in the index.

Adds methods for enumerating pids

---

lib/ddr/models/solr_document.rb

`Ddr::Models::SolrDocument#inherited_license` was improperly deprecated (emits warning w/o current behavior).  Since it appears not to be used by dul-hydra or ddr-public, the method is simply removed.

Removes unused and improperly deprecated method

---

ddr-models.gemspec
lib/ddr/actions/virus_check.rb
lib/ddr/models/engine.rb

Engine initializer sets `Ddr::Antivirus.scanner_adapter` to `:clamd`
for development and production environments; test environment uses
`Ddr::Antivirus.test_mode!`.

Restores usage of ddr-antivirus, now at v2.0.0.rc2.

---

lib/ddr/auth.rb
lib/ddr/auth/grouper_gateway.rb

Use Ddr::Auth.repository_group_filter instead.
Upgrade notes:
- Must set `REPOSITORY_GROUP_FILTER` environment variable if using `Ddr::Auth::GrouperGateway`.
Closes #281

Deprecated Ddr::Auth::GrouperGateway::REPOSITORY_GROUP_FILTER constant.

---

lib/ddr/auth.rb
lib/ddr/models/version.rb

dynamically, rather than setting a statically set module variable.
Fixes #1450
Bumps version to 2.1.3

Ddr::Auth.repository_group_filter returns ENV["REPOSITORY_GROUP_FILTER"]

---

lib/ddr/auth/ability_definitions/datastream_ability_definitions.rb
lib/ddr/models.rb
lib/ddr/models/external_file.rb
lib/ddr/models/has_multires_image.rb
lib/ddr/models/multires_image.rb

@coblej Note that this introduces a MultiresImage object that encapsulates the creation of an MRI as an ExternalFile.  The reason the tests were broken had nothing to do with ability_spec as you can see, but with the multires_image_file_path method in HasMultiresImage.

Fixes ability_spec

---

.travis.yml
lib/ddr/actions/fixity_check.rb
lib/ddr/auth/ability_definitions/role_based_ability_definitions.rb
lib/ddr/datastreams/datastream_behavior.rb
lib/ddr/events/event.rb
lib/ddr/events/fixity_check_event.rb
lib/ddr/managers/derivatives_manager.rb
lib/ddr/managers/permanent_id_manager.rb
lib/ddr/models/governable.rb
lib/ddr/models/licenses/license.rb
lib/ddr/utils.rb
spec/auth/ability_spec.rb
spec/jobs/fits_file_characterization_spec.rb
spec/models/active_fedora_base_spec.rb
spec/models/active_fedora_datastream_spec.rb
spec/models/collection_spec.rb
spec/models/effective_license_spec.rb
spec/models/license_spec.rb
spec/spec_helper.rb
spec/support/shared_examples_for_events.rb
spec/support/shared_examples_for_governables.rb

Fixed some warnings.
Use Deprecation library for deprecations.
Remove bundler caching for Travis CI.

Update deprecated `pid` to `id`.

---

ddr-models.gemspec
lib/ddr/auth/abstract_ability.rb
lib/ddr/models.rb
spec/controllers/including_role_based_access_controls_enforcement_spec.rb
spec/dummy/app/models/solr_document.rb
spec/dummy/app/models/user.rb

Blacklight is a development dependency, mainly for SolrDocument.

Removes dependency on hydra-head gem.

---

lib/ddr/jobs.rb
lib/ddr/jobs/fits_file_characterization.rb
lib/ddr/jobs/job.rb
lib/ddr/jobs/queue.rb
spec/jobs/job_spec.rb

Adds Ddr::Jobs::Queue class to wrap Resque queue info methods.
Extends FitsFileCharacterization job with new module.

Adds Ddr::Jobs::Job module for extending Resque job classes.

---

lib/ddr/jobs/fits_file_characterization.rb
lib/ddr/models.rb
lib/ddr/models/version.rb

Ddr::Jobs::FitsFileCharacterization jobs uses new tempdir setting.
Version 2.3.2

Added `tempdir` config setting to Ddr::Models

---

lib/ddr/jobs/fits_file_characterization.rb
lib/ddr/models.rb
lib/ddr/models/file_characterization.rb
lib/ddr/models/has_content.rb
lib/ddr/models/with_content_file.rb
spec/jobs/fits_file_characterization_spec.rb
spec/models/file_characterization_spec.rb
spec/models/with_content_file_spec.rb

Business logic extracted out to Ddr::Models::FileCharacterization.
Verifies checksum of tempfile (closes #488).
Use backticks for external command execution, replacing Open3 (closes #468).
No longer generates an update event.

Modifications to Ddr::Jobs::FitsFileCharacterization job.

---

lib/ddr/index/fields.rb
spec/index/fields_spec.rb

Returns an array of Field instances for all descriptive metadata fields.

Adds Ddr::Index::Fields.descmd

---

lib/ddr/index/csv_query_result.rb
lib/ddr/index/field_attribute.rb
lib/ddr/index/filter.rb
lib/ddr/index/query.rb
lib/ddr/index/query_builder.rb
lib/ddr/index/query_clause.rb
spec/index/filter_spec.rb
spec/index/query_clause_spec.rb
spec/index/query_spec.rb

The block is passed to a QueryBuilder, hence simplifying the whole bit.
New DSL method: `model`
Some kinks worked out of CSVQueryResult.
Query fields are coerced to Field instances.

Ddr::Index::Query accepts block in initializer.

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

SolrDocument#has_datastream? returns true if the datastream has content and
false if it does not.

Fixes SolrDocument#has_datastream? ; closes #511

---

lib/ddr/derivatives/ptif_generator.rb
lib/ddr/models/version.rb

Runs `identify` on image[0] to determine depth in PTIF generator.

---

lib/ddr/notifications.rb
spec/dummy/config/fedora.yml
spec/dummy/config/solr.yml

Rolls back change in 0fe075c84b7cd6211424123fdf60cf5e61fa636c.
There was no test and it didn't work.
Also adds Fedora and Solr configs to dummy app for AF >= 9.8.0
compatibility (not required for test suite, but for interactive
console).
Closes #536

Removes block params from Ddr::Notifications#notify_event.

---

lib/ddr/managers/permanent_id_manager.rb
lib/ddr/models/version.rb
spec/models/has_admin_metadata_spec.rb

Updates default EZID metadata adding the element "fcrepo3.pid"
to assist in tracking.

Hotfix 2.4.7

---

lib/ddr/datastreams.rb
lib/ddr/models.rb
lib/ddr/models/base.rb
lib/ddr/models/file.rb
lib/ddr/models/metadata/administrative_metadata.rb
lib/ddr/models/metadata/descriptive_metadata.rb
lib/ddr/models/metadata/metadata.rb
spec/models/administrative_metadata_spec.rb
spec/models/descriptive_metadata_spec.rb

Also moves the DESC_METADATA constant from Ddr::Model::File to Ddr::Model::Metadata.

Refactor adminMetadata into a metadata object; closes #550.

---

lib/ddr/index/fields.rb
lib/ddr/models/base.rb
lib/ddr/models/indexing.rb
spec/models/indexing_spec.rb
spec/support/shared_examples_for_ddr_models.rb

`Ddr::Index::Fields::UNIQUE_ID` indexes as searchable (not stored)
and array of unique ids for the object. This includes the Fedora ID,
the permanent ID (if present), and the permanent ID "suffix"
(if permanent ID present) -- i.e., the part of the ARK after the
institutional part (NAAN), a.k.a. the "name".  See
https://wiki.ucop.edu/display/Curation/ARK.
The purpose is to enable one search for unique identifiers.  In
ActiveFedora (subclasses of `Ddr::Models::Base`), use
`.find_by_unique_id(unique_id)`.
Closes #568.

Adds index field for "unique ids"

---

lib/ddr/auth/ability_definitions/collection_ability_definitions.rb
spec/auth/ability_spec.rb

Permission to ingest metadata for collection is granted if have update permission on collection.

Add collection permission for ingesting metadata; closes #574.

---

ddr-models.gemspec
lib/ddr/index/fields.rb
spec/models/has_admin_metadata_spec.rb
spec/support/ezid_mock_identifier.rb

Due to change in how ActiveFedora indexes these attributes.
Also removes unused IS_MEMBER_OF constant.

Revise values of relationship constants; closes #576.

---

lib/ddr/models/base.rb
spec/support/shared_examples_for_ddr_models.rb

This provides a way, for example, for dul-hydra to subscribe to
object save events.

Adds a notification after save to Ddr::Models::Base

---

ddr-models.gemspec
lib/ddr/models/year_facet.rb
spec/models/year_facet_spec.rb

The class has been reoriented to parse dates with edtf-ruby.
Closes #615

Extends Ddr::Models::YearFacet date handling to include several EDTF formats

---

lib/ddr/index/connection.rb
lib/ddr/index/csv_options.rb
lib/ddr/index/csv_query_result.rb
lib/ddr/index/query.rb
lib/ddr/index/solr_csv_options.rb
spec/index/csv_query_result_spec.rb

Adds #delete_empty_columns! method to remove empty columns
from underlying CSV table (closes #599).

Ddr::Index::CSVQueryResult refactored.

---

lib/ddr/models.rb
lib/ddr/models/indexing.rb
spec/models/indexing_spec.rb

Closes #609
Indexed identifier methods available in config Ddr::Models.all_identifiers.

Adds DOI to all_identifiers for indexing.

---

lib/ddr/models/solr_document.rb
lib/ddr/models/version.rb
spec/models/effective_license_spec.rb
spec/models/solr_document_spec.rb
spec/spec_helper.rb

Fixes #628
Adds test coverage for SolrDocument#effective_license.
Deprecates legacy methods of SolrDocument.

Hotfix 3.0.1

---

lib/ddr/models/has_struct_metadata.rb
spec/factories/structure_factories.rb
spec/models/has_struct_metadata_spec.rb
spec/support/structural_metadata_helper.rb

When constructing a default struct_map, if the object being added to the
struct map has a local_id, an ID attribute containing the local_id will
be added to the div element containing that object.

Add local_id to default struct_map; closes #645.

---

lib/ddr/models/base.rb
lib/ddr/models/fixity_check_results.rb
spec/models/indexing_spec.rb

Ddr::Models::Base#attached_files_having_content implements indifferent access

---

lib/ddr/index/query.rb
lib/ddr/index/query_builder.rb
spec/index/query_builder_spec.rb
spec/index/query_spec.rb

The change was made to provide a way to pass in local variables
for evaluation by QueryBuilder.  The latter class was altered to
use instance_exec instead of instance_eval.
Closes #639

Adds class method .build to Ddr::Index::Query

---

lib/ddr/models/base.rb
spec/support/shared_examples_for_ddr_models.rb

This is to support duke-libraries/dul-hydra#1737.

Adds `Ddr::Models::Base#ingest_date`

---

lib/ddr/models/solr_document.rb
spec/models/solr_document_spec.rb

Also renames method to struct_map_ids.

Promote struct_map_pids private method to public; closes #618.

---

lib/ddr/datastreams/descriptive_metadata_datastream.rb
lib/ddr/models/version.rb
spec/models/descriptive_metadata_datastream_spec.rb

:license is now only an Administrative Metadata property.

Remove :license from Descriptive Metadata properties; closes #677.

---

lib/ddr/auth/ability_definitions/collection_ability_definitions.rb
lib/ddr/models/version.rb
spec/auth/ability_spec.rb

The ability is granted if the auth context agents have a policy scope role
that grants the :read permission.
Version 2.4.15

Adds :export ability to Collection

---

lib/ddr/models/base.rb
spec/support/shared_examples_for_ddr_models.rb

Now putting model in event name instead of payload, e.g.
"save.collection".

Changes event name in Ddr::Models::Base#notify_save

---

config/initializers/subscriptions.rb
db/migrate/20161021201011_add_permanent_id_to_events.rb
lib/ddr/events.rb
lib/ddr/events/deaccession_event.rb
lib/ddr/jobs/permanent_id.rb
lib/ddr/models/base.rb
lib/ddr/models/has_admin_metadata.rb
spec/dummy/db/schema.rb
spec/models/events_spec.rb
spec/models/has_admin_metadata_spec.rb
spec/support/shared_examples_for_ddr_models.rb

New event type: `Ddr::Events::Deaccession`.
New instance method for Ddr::Models::Base: `deaccession`.
Callbacks, notifications, and subscriptions adjusted for deletion
events (triggered by `destroy`).

Adds a new event for deaccessioning.

---

app/controllers/users/sessions_controller.rb
lib/ddr/auth.rb

After sign out redirection on servers where Shib authn is required is
handled in Apache conf.
Removed override of `Users::SessionsController#after_sign_out_path_for`
and `Ddr::Auth.sso_logout_url` accessor.
Upgrade note: Remove references to `Ddr::Auth.sso_logout_url` in
local files (e.g., production.rb) if necessary.

Removed redundant code related to sign out.

---

lib/ddr/actions/virus_check.rb
lib/ddr/derivatives/generator.rb
lib/ddr/derivatives/png_generator.rb
lib/ddr/derivatives/ptif_generator.rb
lib/ddr/managers/derivatives_manager.rb

Also remove unneeded 'open3' require in lib/ddr/actions/virus_check.rb.

Remove use of 'open3' in derivatives generation; addresses DDR-294.

---

lib/ddr/models.rb
lib/ddr/models/version.rb

Updates permanent ID target base URL (cherry-picked
from 7b424deb3fe08eb00e365931151e6364d69ddbfc).

Hotfix v2.5.2

---

lib/ddr/managers/permanent_id_manager.rb
lib/ddr/models/version.rb

Updates permanent URL base to https://idn.duke.edu/ (cherry-picked
from 1c4fea5664d8d203717b7977565d93b1cad9d645).
Contributes to DDR-295.

Hotfix v2.5.3

---

lib/ddr/managers/workflow_manager.rb
lib/ddr/models/has_admin_metadata.rb
spec/models/has_admin_metadata_spec.rb

Purpose is to distinguish between unset (initial) workflow state
and workflow state specifically set to "unpublished".

Adds #unpublished? method to WorkflowManager.

---

lib/ddr/models.rb
lib/ddr/models/base.rb
lib/ddr/models/has_admin_metadata.rb
spec/models/has_admin_metadata_spec.rb
spec/support/shared_examples_for_ddr_models.rb

- Deprecates `Ddr::Models::HasAdminMetadata#assign_permanent_id!`.
- Removes after_create callback to assign permanent id (if auto-assign
enabled)
- Removes config setting `Ddr::Models.auto_assign_permanent_ids`.
Upgrade notes:
- Check local config files and remove references to
`Ddr::Models.auto_assign_permanent_ids`.

Adds after_create notification to Ddr::Models::Base

---

lib/ddr/auth/ability_definitions/role_based_ability_definitions.rb
spec/auth/ability_spec.rb

DRYs up Ddr::Auth::RoleBasedAbilityDefinitions to use SolrDocument.find.

---

config/initializers/subscriptions.rb
lib/ddr/models.rb
lib/ddr/models/base.rb
lib/ddr/models/permanent_id.rb
spec/models/permanent_id_spec.rb
spec/support/shared_examples_for_ddr_models.rb

Auto-assignment of permanent ID now happens synchronously in the
after_create callback.

Moves PermanentId class from DulHydra to Ddr::Models.

---

lib/ddr/datastreams/external_file_datastream.rb
lib/ddr/models.rb
lib/ddr/models/engine.rb
spec/spec_helper.rb

Upgrade notes:
- In environment config, expicitly set EITHER
`Ddr::Datastreams::ExternalFileDatastream.file_store`
OR
set `.file_store` on each of the external datastreams:
`Ddr::Datastreams::ContentDatastream`, `Ddr::Datastreams::MultiresImageDatastream`,
and `Ddr::Datastreams::IntermediateFileDatastream`.
- Remove `EXTERNAL_FILE_STORE` and `MULTIRES_IMAGE_EXTERNAL_FILE_STORE` local
environment settings.

Removes legacy custom setting for external file stores.

---

lib/ddr/models/cache.rb
spec/models/cache_spec.rb

Method now returns value of block.

Fixes bug in `Ddr::Models::Cache#with`.

---

ddr-models.gemspec
lib/ddr/models/version.rb

Loosens ezid-client dependency to 1.x (1.6+).

Hotfix v2.6.2.

---

lib/ddr/derivatives/update_derivatives.rb
lib/ddr/models/base.rb
lib/ddr/models/version.rb
spec/support/shared_examples_for_has_content.rb

Adds support for `skip_update_derivatives: true` option to `save`
to bypass derivative generation on object update.

Hotfix v2.7.2

---

lib/ddr/models/file_management.rb
lib/ddr/models/version.rb
spec/models/file_management_spec.rb

Adds :original_filename option to FileManagement#add_file to
support overriding the default usage of the file path.

Hotfix v2.7.4

---

lib/ddr/datastreams/external_file_datastream.rb
lib/ddr/models/version.rb

Fixes Ddr::Datastreams::ExternalFileDatastream#content when
controlGroup is not E by reverting to superclass behavior.

Hotfix v2.7.6

---

lib/ddr/models.rb
lib/ddr/models/file_management.rb
lib/ddr/models/media_type.rb
lib/ddr/utils.rb
spec/models/media_type_spec.rb

For mapping file extensions to preferred media types, especially
for streamable media (DDR-871).
`Ddr::Models::MediaType.call` replaces the now-deprecated method
`Ddr::Utils.mime_type_for`.

Adds `Ddr::Models.preferred_media_types`.

---

lib/ddr/models.rb
lib/ddr/models/base.rb
lib/ddr/models/has_admin_metadata.rb
lib/ddr/models/rights_statement.rb
lib/ddr/models/solr_document.rb
spec/models/rights_statement_spec.rb
spec/models/solr_document_spec.rb
spec/support/shared_examples_for_ddr_models.rb

The new model supersedes `Ddr::Models::License`, which should
be considered deprecated.
Adds `#rights_statement` methods to `Ddr::Models::Base` and
`Ddr::Models::SolrDocument`. These methods supersede
`#effective_license`, which is deprecated and should no
longer be used.
As a transitional measure, `#rights_statement` may return
either a RightsStatement or License instance, depending on
the source of data used. Both models will have the same
attributes and reference the same set of remote data.
After production data has been migrated from dcterms:license
to dcterms:rights, the legacy license methods and models will be
removed.
Completes DDR-867.

Adds new ActiveResource model `Ddr::Models::RightsStatement`.

---

app/models/item.rb
lib/ddr/datastreams/administrative_metadata_datastream.rb
lib/ddr/index/fields.rb
lib/ddr/models/has_content.rb
lib/ddr/models/indexing.rb
lib/ddr/models/solr_document.rb
lib/ddr/vocab/asset.rb
spec/models/indexing_spec.rb
spec/models/item_spec.rb
spec/models/solr_document_spec.rb

Also makes the attribute available on the Item if the Item has one Component.

Add attribute for original filepath to Component.  Addresses DDR-909.

---

app/models/component.rb
config/initializers/active_fedora_base.rb
lib/ddr/datastreams.rb
lib/ddr/datastreams/caption_datastream.rb
lib/ddr/models.rb
lib/ddr/models/captionable.rb
lib/ddr/models/solr_document.rb
spec/fixtures/abcd1234.vtt
spec/models/active_fedora_base_spec.rb
spec/models/component_spec.rb
spec/models/solr_document_spec.rb
spec/support/shared_examples_for_captionable.rb

Caption datastream will have use 'Transcript' in component structural metadata.
Upgrade Note: Add entry for Ddr::Datastreams::CaptionDatastream.file_store to appropriate environment(s).

Add Component datastream for caption file.  DDR-1124.

---

app/models/collection.rb
app/models/component.rb
app/models/item.rb
spec/models/collection_spec.rb
spec/models/component_spec.rb
spec/models/item_spec.rb

Previously, when an object had no structurally relevant associations, the 'default_structure'
method returned nil.  Now, it returns a METS document with an empty structMap element.

An object's default structure is now always an XML document; DDR-1154.

---

lib/ddr/models/base.rb

Need to assign permanent ID before notifying ingest because ingest notification triggers
update of parent structural metadata, which requires that all the children have permanent ID's.

Change the order of the after_create callbacks in Ddr::Models::Base.

---

lib/ddr/datastreams/content_datastream.rb
spec/fixtures/fits/document.xml
spec/fixtures/fits/image.xml
spec/managers/technical_metadata_manager_spec.rb
spec/support/shared_examples_for_has_content.rb

This was done to confirm that there no changes are required to
metadata mappings.
Adds around_save notification to content datastream.

Updates FITS test fixtures to FITS 1.2.0 output.

---

lib/ddr/datastreams/external_file_datastream.rb
spec/datastreams/external_file_datastream_spec.rb

Fixes bug in ExternalFileDatastream#content that causes ingest to
fail with a very large file. The fix alters the behavior to read
the external file (with File.read) only if the datastream is
persisted.

Hotfix 2.9.2

---

lib/ddr/index/connection.rb

Use POST instead of GET in Solr requests.

---

lib/ddr/models/base.rb
spec/models/permanent_id_spec.rb

This should correct timing issues affecting structural metadata
generation per DDR-1391.

Moves permanent ID minting from after_create to around_save callback.

---

ddr-models.gemspec
lib/ddr/models/version.rb

Upgrades net-ldap to ~> 0.16.
Addresses reported security vulnerability.

Hotfix 2.10.1
